version: '3.8'

services:
  "{{cookiecutter.project_slug}}-api":
    user: root
    image: "{{cookiecutter.project_slug}}-api:0.1"
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      CACHE_PATH: "/code/data"
    ports:
      - "8000:8000"
    volumes:
      - ./src/api/:/code/api
      - ../{{cookiecutter.project_slug}}-cache:/code/data
    command: fastapi dev main.py --host 0.0.0.0 --port 8000
